openapi: 3.0.0
info:
  title: Holidays API
  version: 1.0.0
  description: API to manage holidays
servers:
  - url: http://localhost:3000/api
    description: API server
tags:
  - name: Holidays
    description: API to manage holidays

paths:
  /holidays:
    get:
      summary: Get holidays by country and year
      tags:
        - Holidays
      parameters:
        - name: country
          in: query
          description: Country code (e.g., PK)
          required: true
          schema:
            type: string
        - name: year
          in: query
          description: Year for the holidays (e.g., 2024)
          required: true
          schema:
            type: integer
      responses:
        200:
          description: A list of holidays
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      example: "2024-01-01"
                    name:
                      type: string
                      example: "New Year's Day"
        500:
          description: Error fetching holidays

  /countries:
    get:
      summary: Get a list of countries
      tags:
        - Holidays
      responses:
        200:
          description: A list of countries
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    country_name:
                      type: string
                    flag_unicode:
                      type: string
                    iso-3166:
                      type: string
                    supported_languages:
                      type: integer
                    total_holidays:
                      type: integer
        500:
          description: Error fetching countries
